<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <a class="btn-floating right" href="/my/repo/add/" title="添加GIT库"><i class="fa fa-plus"></i> </a>
                <span class="card-title"><a href="/my/repo/">我创建的GIT库</a></span>

                <ul class="collection">
                    <?php foreach ($repos as $repo): ?>
                        <li class="collection-item">
                            <a href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/"><?= $repo['group'] ?>
                                /<?= $repo['name'] ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title"><a href="/my/repo/belone/">我拥有的GIT库</a></span>

                <ul class="collection">
                    <?php foreach ($brepos as $repo): ?>
                        <li class="collection-item">
                            <a href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/"><?= $repo['group'] ?>
                                /<?= $repo['name'] ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
</div>
