<?php include 'include-tabs.phtml' ?>

<h3><?= $commit['msg'] ?></h3>
<div class="card">
    <div class="card-content">
        <?= substr($commit['commit'], 0, 8) ?>&nbsp;<?= $commit['author']['name'] ?> 提交于 <?= date('y/m/d H:i', $commit['author']['date']) ?><br/>
        <?php switch (count($commit['parent'])):
            case 0:
                break;
            case 1:
                echo '上一个提交：';
                break;
            case 2:
                echo '合并请求：';
                break;
        endswitch;
        ?>
        <?php foreach ($commit['parent'] as $parent): ?>
            <a href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/commit/<?= $parent ?>/"><?= substr($parent, 0,
                    8) ?></a>
        <?php endforeach ?>
        &nbsp;所在分支：
        <?php foreach($branches as $_branch):?>
            <a href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/tree/<?=$_branch['name']?>/"><?=$_branch['name']?></a>
        <?php endforeach?>
    </div>
</div>
<?= $commit['tstats']['file'] ?>个文件发生变化，<?php if ($commit['tstats']['insect']): ?>增加<?= $commit['tstats']['insect'] ?>行，<?php endif ?>
<?php if ($commit['tstats']['delete']): ?>删除<?= $commit['tstats']['delete'] ?>行<?php endif ?>。

<ul class="collection">
    <?php foreach ($commit['stats'] as $key => $stat): ?>
        <li class="collection-item">
            <?= $key + 1 ?>.&nbsp;
            <?php if ($stat['insect'] != 0 || $stat['delete'] != 0): ?>
                <a href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/diff/<?= $branch ?>/<?= $stat['file'] ?>"><?= $stat['file'] ?></a>
                &nbsp;&nbsp;
                <?php if ($stat['insect']): ?>
                    <small>+<?= $stat['insect'] ?></small>&nbsp;<?php endif ?>
                <?php if ($stat['delete']): ?>
                    <small>-<?= $stat['delete'] ?></small><?php endif ?>
            <?php else: ?>
                <?= $stat['file'] ?>
            <?php endif ?>
            <div style="display:none"></div>
        </li>
    <?php endforeach ?>
</ul>

<script>
    $('.collection-item > a').on('click', function () {
        var next = $(this).nextAll('div').eq(0);
        if (!next.html()) {
            $.get(this.href, function (html) {
                next.html(html);
            });
        }
        next.toggle();
        return false;
    });
</script>