<?php include 'include-tabs.phtml' ?>
<?php include 'include-branches.phtml' ?>

<?php if ($commits): ?>
    <table class="striped bordered card-panel">
        <thead>
        <tr>
            <th width="15%">版本号</th>
            <th>提交信息</th>
            <th width="12%">提交日期</th>
            <th width="8%">作者</th>
        </tr>
        </thead>
        <tbody>
        <?php include 'include-commits.phtml' ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4" class="center-align">
                <a class="btn" data-hook="next"
                   data-url="/repo/ncommits/{next}/?_of=json&repo_id=<?= $repo['repo_id'] ?>" data-next="<?= $next ?>">下一页</a>
            </td>
        </tr>
        </tfoot>
    </table>
    <script>
        $('table tfoot a[data-hook="next"]').each(function () {
            var self = $(this), tfoot = self.parents('tfoot');
            self.on('click', function () {
                if (self.data('next')) {
                    var url = self.data('url').replace('{next}', self.data('next'));
                    $.ajax({
                        url: url,
                        success: function (ret) {
                            tfoot.prev('tbody').append(ret.data.html);
                            if (ret.data.next) {
                                self.data('next', ret.data.next);
                            } else {
                                tfoot.hide();
                                self.data('next', '');
                            }
                        }
                    })
                }
                return false;
            });
        });
    </script>
<?php else: ?>
    <div class="card-panel">还没有任何提交</div>
<?php endif ?>
