<h4><a href="/<?= $repo['group'] ?>/"><?= $repo['group'] ?></a>/<a href="/<?=$repo['group']?>/<?=$repo['name']?>/"><?= $repo['name'] ?></a></h4>
<ul class="tabs">
    <li class="tab"><a target="_self" <?=$repoNav == 'code' ? ' class="active"' : ''?> href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/">代码</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'commit' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/commit/">提交</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'branch' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/branch/">分支</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'tag' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/tag/">标签</a></li>
</ul>
<?php if(!empty($showSummary)):?>
    <p><?=$repo['summary']?></p>
<?php endif?>
