<div class="row">
    <h4 class="col s9"><a href="/<?= $repo['group'] ?>/"><?= $repo['group'] ?></a>/<a href="/<?=$repo['group']?>/<?=$repo['name']?>/"><?= $repo['name'] ?></a></h4>
    <div class="col s3" style="padding-top:0.4rem"><input class="center-align" value="<?=$gitUrl?>" onmouseenter="this.select();"/></div>
</div>
<ul class="tabs">
    <li class="tab"><a target="_self" <?=$repoNav == 'code' ? ' class="active"' : ''?> href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/">代码</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'commits' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/commits/">提交</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'branches' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/branches/">分支</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'tags' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/tags/">标签</a></li>
    <li class="tab"><a target="_self" <?=$repoNav == 'member' ? ' class="active"' : ''?>href="/<?= $repo['group'] ?>/<?= $repo['name'] ?>/member/">成员</a></li>
</ul>

<?php if(!empty($showSummary)):?>
    <p><?=$repo['summary']?></p>
<?php endif?>
