<h4><a href="/<?=$repo['group']?>/"><?=$repo['group']?></a>/<?=$repo['name']?></h4>
<ul class="tabs">
    <li class="tab"><a target="_self" class="active" href="/<?=$repo['group']?>/<?=$repo['name']?>/">代码</a></li>
    <li class="tab"><a target="_self" href="/<?=$repo['group']?>/<?=$repo['name']?>/commit/">提交</a></li>
    <li class="tab"><a target="_self" href="/<?=$repo['group']?>/<?=$repo['name']?>/branch/">分支</a></li>
    <li class="tab"><a target="_self" href="/<?=$repo['group']?>/<?=$repo['name']?>/tag/">标签</a></li>
</ul>
<p><?=$repo['summary']?></p>

<ul class="collection">
    <?php foreach($files['dir'] as $dir):?>
        <li class="collection-item">
            <a href="/<?=$repo['group']?>/<?=$repo['name']?>/<?=$branch?>/tree/<?=$dir['path']?>/"><?=$dir['name']?></a>
        </li>
    <?php endforeach?>
    <?php foreach($files['file'] as $file):?>
        <li class="collection-item">
            <a href="/<?=$repo['group']?>/<?=$repo['name']?>/<?=$branch?>/blob/<?=$file['path']?>"><?=$file['name']?></a>
        </li>
    <?php endforeach?>
</ul>