<h1>登录</h1>
<form method="post" action="/account/_login" data-hook="ajax" data-rurl="/" data-success="登录成功">
    <div class="input-field">
        <input name="username" type="text" class="validate" required autofocus>
        <label>帐号/邮箱</label>
    </div>
    <div class="input-field">
        <input name="password" type="password" class="validate" required maxlength="20">
        <label>密码</label>
    </div>
    <button class="btn waves-effect waves-light" type="submit" name="action">
        <i class="fa fa-sign-in right"></i>登录
    </button>
</form>