<h2>添加用户</h2>

<form method="post" action="/gl/user/_add" data-hook="ajax" data-success="添加成功">
    <input type="hidden" value="<?= $user['user_id'] ?>" name="user_id"/>
    <div class="input-field">
        <input name="username" type="text" class="validate" value="" required autofocus minlength="6" maxlength="20" pattern="^[a-z][a-zA-Z0-9\.\_\-]{5,19}$"/>
        <label>帐号</label>
    </div>
    <div class="input-field">
        <input id="newpwd" type="password" name="newpwd" class="validate" required minlength="6" maxlength="12" pattern="^\w{6,12}$"/>
        <label for="newpwd">新密码(6-20位)</label>
    </div>
    <div class="input-field">
        <input id="repwd" type="password" name="repwd" class="validate"/>
        <label for="repwd">重复输入密码</label>
    </div>
    <div class="input-field">
        <input name="email" type="email" class="validate" required value="">
        <label>邮箱</label>
    </div>
    <div class="input-field">
        <input name="realname" type="text" class="validate" required value="" minlength="2" maxlength="20">
        <label>真实姓名</label>
    </div>
    <div>
        <label>角色</label>
        <?php foreach($roles as $roleId => $roleName):?>
            <p>
                <input class="with-gap" type="radio" <?=$roleId == 1 ? ' checked' : ''?> value="<?=$roleId?>" name="role" id="role<?=$roleId?>">
                <label for="role<?=$roleId?>"><?=$roleName?></label>
            </p>
        <?php endforeach?>
    </div>
    <div class="input-field">
        <input name="phone" type="number" class="validate" value="" minlength="11" maxlength="11">
        <label>电话</label>
    </div>
    <button class="btn waves-effect waves-light" type="submit" name="action">
        添加
    </button>
    &nbsp;&nbsp;<a href="/gl/user/">返回</a>
</form>
<script src="/dist/firegit/js/password.js"></script>