<?php include 'include-nav.phtml' ?>
<h2>修改密码</h2>

<form method="post" action="/my/_password/" data-hook="ajax" id="formPwd" data-success="密码修改成功，请重新登录" rurl="/account/login">
    <div class="input-field">
        <input id="oldpwd" type="password" name="oldpwd" class="validate" required/>
        <label for="oldpwd">旧密码</label>
    </div>
    <div class="input-field">
        <input id="newpwd" type="password" name="newpwd" class="validate" required minlength="6" maxlength="20"
               pattern="^\w{6,12}$"/>
        <label for="newpwd">新密码(6-20位)</label>
    </div>
    <div class="input-field">
        <input id="repwd" type="password" name="repwd" class="validate"/>
        <label for="repwd">重复输入密码</label>
    </div>
    <div>
        <button class="btn waves-effect waves-light" type="submit" name="action">修改</button>
    </div>
</form>

<script src="/dist/firegit/js/password.js"></script>