<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="/dist/materialize/css/materialize.min.css"/>
    <script src="/dist/jquery/jquery.min.js"></script>
    <script src="/dist/vue/vue.min.js"></script>
    <script src="/dist/materialize/js/materialize.min.js"></script>
    <title>Firegit</title>
    <style>
        main .container{width:100%;padding:.5rem;}
    </style>
</head>
<body>
<header>
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">Firegit</a>
        <ul class="hide-on-med-and-down" style="margin-left:7rem;">
            <li class="active"><a href="/">首页</a></li>
            <li><a href="/repo/">GIT库</a></li>
            <li><a href="/merge/">合并请求</a></li>
        </ul>
    </div>
</nav>
</header>
<main>
    <div class="container">
        <?=$content?>
    </div>
</main>
<footer>

</footer>
</body>
</body>
</html>